dcsaorg/P6-Application

- .github/workflows/docker-publish.yml
- ui/Dockerfile
- ui/docker-compose.yml
- ui/nginx.d/default.conf.template
> Add Dockerfile + compose

- .github/workflows/docker-publish.yml
- ui/Dockerfile
- ui/docker-compose.yml
- ui/nginx.d/default.conf.template
> Re-add docker resurses

- ui/src/app/app-routing.module.ts
- ui/src/app/auth/auth-interceptor.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.ts
- Auth is disabled for local and **enabled** for production env.
> DDT-302-auth-local-dev-enviroment

- ui/src/app/controller/pipes/operations-event-to-timestamp-type.pipe.ts
- Align facilityTypeCode to operationsEvent
- return null when there is no matches 
- fix syntax
> Update operations-event-to-timestamp-type pipe function 

- ui/Dockerfile
> Docker: Install assets in correct directory

- ui/src/app/app-routing.module.ts
- This should have been caught and included as part of #36
> Guard dashboard when routing to transportCall

- ui/src/app/auth/auth.service.ts
> Correct the Authorization header

- ui/src/app/app.module.ts
- ui/src/app/auth/auth.service.ts
- ui/src/app/auth/sign-up/sign-up.component.ts
- ui/src/app/controller/services/base/config.service.ts
- ui/src/app/controller/services/base/export.service.ts
- ui/src/app/controller/services/base/vessel.service.ts
- ui/src/app/controller/services/ovs/operations-event.service.ts
- ui/src/app/controller/services/ovs/timestamps.service.ts
- ui/src/app/controller/services/ovs/transport-call.service.ts
- ui/src/app/controller/services/static/static-config.service.ts
- ui/src/app/model/ovs/config.ts
- ui/src/app/view/header/header.component.ts
- ui/src/assets/config.json
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.ts
- ui/src/proxy.conf.json
> Move more configuration to config.json

- ui/src/app/controller/pipes/timestamp-to-standardized-timestamp.ts
- ui/src/app/view/header/header.component.ts
> Fix references to config

- ui/angular.json
- ui/src/app/view/vessel-editor/vessel-editor.component.ts
- fix default for vesselFlag
- remove unused imports
> minor fixes

- ui/src/app/view/timestamp-table/timestamp-table.component.html
- ui/src/app/view/timestamp-table/timestamp-table.component.scss
- ui/src/app/view/timestamp-table/timestamp-table.component.ts
- ui/src/app/view/transport-calls-table/transport-calls-table.component.scss
+ fixed the alignment for buttons in general
> fixed the positions of refresh button for timestamp table

- ui/src/assets/static_data/ports.json
> ports.json: Make human maintainable and correct some timezones

- ui/src/app/controller/services/ovs/timestamps.service.ts
Compared the respective cases for different publishers
> update timestamps.service cases

- ui/src/app/controller/pipes/timestamp-to-standardized-timestamp.ts
- ui/src/app/view/timestamp-editor/timestamp-editor.component.ts
- ui/src/app/view/transport-call-creator/transport-call-creator.component.ts
Converts the submitted date-time when creating a timestamp to UTC according to the timezone of the selected port of call.
> Fix for date-time in Timestamp

- ui/src/app/controller/services/base/export.service.ts
> Correct URL to excel download

- ui/src/app/model/portCall/portcall-timestamp-type.enum.ts
- ui/src/app/view/timestamp-table/timestamp-table.component.html
- ui/src/app/view/timestamp-table/timestamp-table.component.ts
- ui/src/app/view/vessel-editor/vessel-editor.component.html
- ui/src/app/view/vessel-editor/vessel-editor.component.ts
- ui/src/assets/i18n/en.json
-     Make everything except IMO + name optional (DONE)
-     On edit: IMO cannot change! (DONE)
-     Comment: Any information you want to you share? (rather than "only a delay") (DONE)
-     Timestamp: Sort DESC on eventCreatedDateTime (DONE)
-     Sorting of timestamp ATS Pilot(age) between other ATX timestamp (DONE)
-     ATS Pilot -> ATS Pilotage (DONE)
> DDT-331-minor-improvs

- ui/src/app/controller/services/mapping/timestamp-mapping.service.ts
- ui/src/app/model/enums/facilityTypeCodeOPR.ts
- ui/src/app/view/transport-call-creator/transport-call-creator.component.html
- ui/src/app/view/transport-call-creator/transport-call-creator.component.scss
- ui/src/app/view/transport-call-creator/transport-call-creator.component.ts
improved the size of the textarea aswell
> removed facilityTypeCode from transportcall-creater

- ui/src/app/view/dashboard/dashboard.component.ts
We now ensure that ports are loaded for transportcall-id routing
> Fix for transport-call id routing

- ui/src/app/view/transport-calls-table/transport-calls-table.component.html
- ui/src/app/view/transport-calls-table/transport-calls-table.component.scss
- ui/src/app/view/transport-calls-table/transport-calls-table.component.ts
Very nice to have from my point of view :)
> progress indicator added to TC table

- ui/src/app/view/timestamp-table/timestamp-table.component.scss
See https://github.com/cssnano/cssnano/pull/881
> Rewrite opacity declaration

- ui/src/app/controller/pipes/operations-event-to-timestamp.pipe.ts
- ui/src/app/controller/services/mapping/timestamp-mapping.service.ts
- ui/src/app/model/eventLocation.ts
- ui/src/app/model/ovs/operations-event.ts
- ui/src/app/model/ovs/timestamp.ts
- ui/src/app/view/timestamp-table/timestamp-table.component.html
- ui/src/app/view/timestamp-table/timestamp-table.component.ts
- Terminal-ID is retrieved from timestamp as opposed to transportcall following OVS#2.0.3
> DDT-433-retrieve-terminal

- ui/src/app/view/dashboard/dashboard.component.scss
- possible to expand the functionality of the sliders, but works for now.
Drag the sliders in the bottom right corner of the tables.
> Table sliders

- ui/src/app/view/instructions/instructions.component.html
- ui/src/assets/i18n/en.json
> Update instructions (from Guido)

- ui/src/app/controller/services/base/timestamp-definition.service.ts
- ui/src/app/model/jit/timestamp-definition.ts
- ui/src/app/view/timestamp-table/timestamp-table.component.html
- ui/src/app/view/timestamp-table/timestamp-table.component.ts
> Ensure we show the correct timestamp name in Accept tooltip

- ui/src/app/controller/services/base/timestamp-definition.service.ts
- ui/src/app/controller/services/jit/transport-call.service.ts
> Improve filtering in the UI

- ui/src/app/controller/services/jit/transport-call.service.ts
- ui/src/app/model/jit/transport-call.ts
- ui/src/app/view/transport-calls-table/transport-calls-table.component.html
- ui/src/app/view/transport-calls-table/transport-calls-table.component.scss
displaying transportcalls with ATD Berth as obsolete and greyed out
> displaying transportcalls with ATD Berth as obsolete and greyed out

- .github/workflows/docker-publish.yml
> CI: Build images for all live-* branches

- ui/package-lock.json
> Bump trivial dependencies (npm audit fix)

- src/app/controller/pipes/vessel-tooltip.pipe.ts
- src/app/model/jit/transport-call.ts
- src/app/model/portCall/vessel.ts
- src/app/view/transport-calls-table/transport-calls-table.component.html
added vesselDraft and milesRemainingToDestination to the UI as mouse-over tooltip in both the Vessel Name and the IMO Number fields in the transportcalls.
Depends on #165
> DDT-1130: draft mielsremaning mouseover

- package.json
- src/app/controller/pipes/operations-event-to-timestamp.pipe.ts
- src/app/controller/pipes/operations-events-to-timestamps.pipe.ts
- src/app/controller/pipes/timestamp-to-standardized-timestamp.ts
- src/app/controller/services/base/timestamp-definition.service.ts
- src/app/controller/services/mapping/timestamp-mapping.service.ts
- src/app/model/jit/publisher-pattern.ts
- src/app/model/jit/timestamp-definition.ts
- src/app/model/jit/timestamp.ts
- src/app/model/jit/timestampInfo.ts
- src/app/view/timestamp-accept-editor/timestamp-accept-editor.component.ts
- src/app/view/timestamp-editor/timestamp-editor.component.html
- src/app/view/timestamp-editor/timestamp-editor.component.ts
- src/app/view/timestamp-table/timestamp-table.component.ts
- src/app/view/transport-call-creator/transport-call-creator.component.ts
- added function to align PR with publisher pattern
- added function to ensure ensure VoyageNumbers are defined (JIT 1.1)
- add eventDeliveryStatus to timestamp
- minor optimizations
> DDT-1148 : Align timestamp definitions

- DCSA-Theme.scss
- solves sticky header issue on TC table
> DDT-1153: add css rule for overflow-x

- src/app/controller/pipes/operations-event-to-timestamp.pipe.ts
- src/app/controller/pipes/timestamp-to-standardized-timestamp.ts
- src/app/model/jit/timestamp-definition.ts
- src/app/view/timestamp-accept-editor/timestamp-accept-editor.component.html
- src/app/view/timestamp-accept-editor/timestamp-accept-editor.component.ts
- src/app/view/timestamp-editor/timestamp-editor.component.html
- src/app/view/timestamp-editor/timestamp-editor.component.ts
- src/app/view/transport-call-creator/transport-call-creator.component.html
- src/app/view/transport-call-creator/transport-call-creator.component.ts
- src/assets/i18n/en.json
- Enforce validators on milesToDestinationPort
- enforce validators on vessel position
- add lang & syntax
> DDT-1168: add milesToDestinationPort option & more

- src/app/model/jit/transport-call.ts
- src/app/view/timestamp-table/timestamp-table.component.html
- src/app/view/timestamp-table/timestamp-table.component.scss
- src/app/view/timestamp-table/timestamp-table.component.ts
- src/app/view/transport-call-creator/transport-call-creator.component.ts
- src/app/view/transport-calls-table/transport-calls-table.component.html
- src/app/view/transport-calls-table/transport-calls-table.component.scss
- src/app/view/transport-calls-table/transport-calls-table.component.ts
Depends on:
* https://github.com/dcsaorg/DCSA-Information-Model/pull/344
* https://github.com/dcsaorg/DCSA-UI-Support/pull/64
> DDT-1164: Highlight timestamps/transport call that are OMIT'ed

- src/app/view/timestamp-editor/timestamp-editor.component.html
- src/app/view/timestamp-editor/timestamp-editor.component.ts
- src/app/view/transport-call-creator/transport-call-creator.component.ts
- src/assets/i18n/en.json
Based on #220  should **not** be merged before.
> DDT-1201: Terminal validation

- src/app/controller/services/mapping/timestamp-mapping.service.ts
- src/app/model/enums/dimensionUnit.ts
- src/app/model/enums/draftUnit.ts
- src/app/model/enums/vesselType.ts
- src/app/model/jit/operations-event.ts
- src/app/model/jit/timestamp.ts
- src/app/model/jit/transport-call.ts
- src/app/model/portCall/vessel.ts
- src/app/view/timestamp-editor/timestamp-editor.component.ts
- src/app/view/transport-call-creator/transport-call-creator.component.ts
- src/app/view/vessel/vessel.component.ts
> DDT-1199: Provide vessel object on POST /timestamp

- src/app/controller/services/base/timestamp-definition.service.ts
- src/app/controller/services/jit/timestamp-info.service.ts
- src/app/controller/services/mapping/timestamp-mapping.service.ts
- src/app/view/timestamp-table/timestamp-table.component.html
- src/app/view/timestamp-table/timestamp-table.component.ts
- src/assets/i18n/en.json
> DDT-1204: backend filtering NegotiationCycle

- .github/workflows/docker-publish.yml
- Dockerfile
> Have docker build be self-contained

- src/app/model/portCall/vessel.ts
- src/app/view/vessel-editor/vessel-editor.component.html
- src/app/view/vessel-editor/vessel-editor.component.ts
- src/app/view/vessel/vessel.component.ts
- src/assets/i18n/en.json
- Enforce dimensionUnit for length & width dimensions
> DDT-1212: add JIT 1.2 vessel fields to dialog

- .github/workflows/docker-publish.yml
> Also create docker images on publish

- angular.json
- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/controller/services/base/port.service.ts
- src/app/controller/services/base/publisher-role.service.ts
- src/app/controller/services/base/timestamp-definition.service.ts
- src/app/controller/services/base/transport-call-filter.service.ts
- src/app/controller/services/base/vessel.service.ts
- src/app/model/enums/publisherRole.ts
- src/app/model/enums/vesselType.ts
- src/app/model/jit/timestamp.ts
- src/app/model/portCall/vessel.ts
- src/app/view/dashboard/dashboard.component.html
- src/app/view/dashboard/dashboard.component.ts
- src/app/view/port-of-call/port-of-call.component.ts
- src/app/view/timestamp-editor/timestamp-editor.component.html
- src/app/view/timestamp-editor/timestamp-editor.component.ts
- src/app/view/timestamp-table/timestamp-table.component.ts
- src/app/view/transport-call-creator/transport-call-creator.component.html
- src/app/view/transport-call-creator/transport-call-creator.component.ts
- src/app/view/transport-calls-table/transport-calls-table.component.html
- src/app/view/transport-calls-table/transport-calls-table.component.scss
- src/app/view/transport-calls-table/transport-calls-table.component.ts
- src/app/view/vessel-editor/vessel-editor.component.html
- src/app/view/vessel-editor/vessel-editor.component.ts
- src/app/view/vessel/vessel.component.html
- src/app/view/vessel/vessel.component.ts
- src/assets/i18n/en.json
- tslint.json
Closes: https://github.com/dcsaorg/P6-Application/pull/257
Closes: https://github.com/dcsaorg/P6-Application/pull/258
> DDT-1237+DDT-1239: Improve length + width in the vessel editor

- src/app/controller/services/base/timestamp-definition.service.ts
- src/app/controller/services/jit/timestamps.service.ts
- src/app/model/portCall/port-call-part.ts
- src/app/view/timestamp-editor/timestamp-editor.component.ts
- src/app/view/timestamp-table/timestamp-table.component.html
- src/app/view/timestamp-table/timestamp-table.component.ts
- src/app/view/transport-calls-table/transport-calls-table.component.ts
> DDT-1246: OMIT and ATD-Berth needs to reload selected TC

- src/app/model/jit/timestamp-definition.ts
- src/app/view/timestamp-editor/timestamp-editor.component.html
> DDT-1241: Conditionally show vessel draft field

- Dockerfile
- src/assets/config.json
- src/proxy.conf.json
> Update context to include /jit + /ui-support

- DCSA-Theme.scss
- src/app/controller/services/base/timestamp-definition.service.ts
- src/app/view/dashboard/dashboard.component.ts
- src/app/view/timestamp-editor/timestamp-editor.component.html
- src/app/view/timestamp-editor/timestamp-editor.component.ts
- src/app/view/transport-call-creator/transport-call-creator.component.html
- src/app/view/transport-call-creator/transport-call-creator.component.ts
- src/app/view/vessel-editor/vessel-editor.component.html
- src/app/view/vessel-editor/vessel-editor.component.ts
Some where and others were not.  For now, we consistently use the border color as a means to show required fields.
Fix two additional bugs while I was at it.
> DDT-1371: Make all required fields visible immediately.
